### ISSUE TITLE
How does multi-domain support work in clofus-chatbot?

### ISSUE THREAD

**Issue by jeffzhengye** [clofus/clofus-chatbot#2]
Hi. I saw the claim that clofus is the only multi-domain support using rasa, but I didn't find how it works.
Could anyone give me any hints regarding multi-domain support? via web-ui or code are both good to me. thanks.

**Comment by karthikbalu** [comment]
Our idea is very simple...

Just by keeping different folders for different domains with its story, nlu, actions and running them as HTTP server each domains with separate server port in parallel

I have a nodejs proxy REST interface that routes request to corresponding python HTTP server port based on the selected agent domain given as part of the input message, already Rasa Core has the HTTP server with sender id tracking etc., so i felt its a good idea not to reinvent the wheel here

Pls Let me know what are the down side of this approach other than port exhaustion?
Thanks

**Comment by jeffzhengye** [comment]
@karthikbalu  thanks for you reply.
**the selected agent domain given as part of the input message**
The problem is you cannot know which agent to use before routing, unless you create a classifier to do this.  If you have many agents, you have to turn and update this classifier. This solution is impractical.  

Any viable suggestion for having many agents?

**Comment by karthikbalu** [comment]
Our use case is different, we are using multiple agents for serving multiple clients working on isolated domains as opposed to ur idea of using multiple domains for same client
