### ISSUE TITLE
How to used the trained models

### ISSUE THREAD

**Issue by wzpan** [clofus/clofus-chatbot#3]
Hello, I've trained and tested the robot and they are satisfying.

Now how to used them in my product? Is there any restful API reference?

**Comment by wzpan** [comment]
I got it. Here's the API URLs' `curl` examples:

* rasa-nlu parse: 

```
curl -XPOST IP:PORT/conversations/default/parse -d '{"query":"hello"}'
```

* rasa-core conversation:

```
curl -XPOST IP:PORT/conversations/default/continue -d '{"executed_action":"utter_hello", "events": []}'
```

**Comment by wzpan** [comment]
I still have a problem: how to get the response templates?

**Comment by wzpan** [comment]
Seems like I don't need to call the above rasa-nlu api. 

Simply call the clofus API with headers `{'Content-Type':'application/x-www-form-urlencoded'}` works. For example:

``` sh
curl http://IP:PORT/api/v1/conversations/default/parse?id=ID --header '{"Content-Type":"application/x-www-form-urlencoded"}' -d '{"query":"hello"}'
```

**Comment by karthikbalu** [comment]
Pls contact me at karthikbalu.meng@gmail.com
